global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'email@email.com'
  smtp_auth_username: 'email@email.com'
  #smtp_auth_password: 'password'
  smtp_auth_password_file: /run/secrets/smtp_password
  smtp_require_tls: true

route:
  receiver: 'email-alert'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'email@email.com'
