services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus           # Prometheus config
      - prometheus_data:/prometheus            # Prometheus data
      - ./certs/monitoring.crt:/etc/prometheus/monitoring.crt:ro
      - ./certs/monitoring.key:/etc/prometheus/monitoring.key:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.config.file=/etc/prometheus/web-config.yml"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana          # Grafana data
      - ./certs/monitoring.crt:/etc/grafana/monitoring.crt:ro
      - ./certs/monitoring.key:/etc/grafana/monitoring.key:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      - prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
#    ports:
#      - "9100:9100"
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager       # Alertmanager config
#    ports:
#      - "9093:9093"
    command:
      - "--config.file=/etc/alertmanager/config.yml"
    networks:
      - monitoring

  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    volumes:
      - ./snmp-exporter:/etc/snmp-exporter     # SNMP Exporter config
    ports:
      - "9116:9116"                            # Default SNMP Exporter port
    command:
      - "--config.file=/etc/snmp-exporter/snmp.yml"
    networks:
      - monitoring

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.97.0
    container_name: victoriametrics
#    ports:
#      - "8428:8428" # Port d'accès HTTP
    volumes:
      - ./victoriametrics:/victoria-metrics-data # Pour la persistance des données
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
