global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          environment: 'dev'
          role: 'monitoring'


  - job_name: 'win-exporter'
    static_configs:
      - targets: ['FQDN:9182', 'FQDN:9182']


  - job_name: 'snmp'
    static_configs:
      - targets:
          - 192.168.1.1      # Adresse IP de l'équipement SNMP
    metrics_path: /snmp
    params:
      module: [default]       # Utilise le module "default" défini dans snmp.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116  # Adresse du SNMP Exporter

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'  # Ensure this points to the correct address and port

rule_files:
  - "alert_rules.yml"

