global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          environment: 'dev'
          role: 'monitoring'


  - job_name: 'win-exporter'
    static_configs:
      - targets: ['FQDN:9182', 'FQDN:9182']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'  # Ensure this points to the correct address and port

rule_files:
  - "alert_rules.yml"