global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'FRPONSUPERVISION-01.novalys.fr'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          environment: 'dev'
          role: 'monitoring'

  - job_name: 'win-exporter'
    static_configs:
      - targets: ['FRPONAD-01.novalys.fr:9182', 'FRPONAD-02.novalys.fr:9182', 'FRPONVEEAM-01.novalys.fr:9182', 'FRPONADCONNECT.novalys.fr:9182', 'FRPONRADIUS-01.novalys.fr:9182']

  - job_name: 'FRPONPFSENSE-01.novalys.fr'
    metrics_path: /snmp
    params:
      module: [if_mib]
      auth: [public_v2]
    static_configs:
      - targets:
        - 192.168.1.230
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116

  - job_name: 'FRPONPFSENSE-02.novalys.fr'
    metrics_path: /snmp
    params:
      module: [if_mib]
      auth: [public_v2]
    static_configs:
      - targets:
        - 192.168.1.240
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'  # Ensure this points to the correct address and port

rule_files:
  - "alert_rules.yml"

remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"
