# https://prometheus.io/docs/prometheus/latest/configuration/https/
tls_server_config:
  cert_file: /etc/prometheus/prometheus.crt
  key_file: /etc/prometheus/prometheus.key

basic_auth_users:
    <ID>: <secret>